-- =============================================================================
-- JurisCore V4 — case documents
--
-- Metadata only. The bytes live in S3 and never touch PostgreSQL: a bytea column
-- holding filings would make every backup, replica and dump carry the whole
-- corpus, and would put the file through the application heap on the way in and
-- out. `storage_key` is the join between the two, and it is generated by the
-- platform — never by a caller — so no user input reaches an object path.
--
-- Same rules as V1-V3: one schema per module, no foreign keys leaving it.
-- case_id points into casework.cases and is therefore a plain UUID column,
-- validated through CaseAccess before anything is written.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS documents;

CREATE TABLE documents.case_documents
(
    id                UUID          PRIMARY KEY,
    version           BIGINT        NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ   NOT NULL,
    updated_at        TIMESTAMPTZ   NOT NULL,
    created_by        UUID,
    updated_by        UUID,

    organization_id   UUID          NOT NULL,
    case_id           UUID          NOT NULL,

    original_filename VARCHAR(255)  NOT NULL,
    content_type      VARCHAR(255)  NOT NULL,
    file_size         BIGINT        NOT NULL,
    -- organizations/{org}/cases/{case}/documents/{id}. Unique globally, because a
    -- second row pointing at the same object would mean deleting one silently
    -- breaks the other.
    storage_key       VARCHAR(512)  NOT NULL,
    status            VARCHAR(32)   NOT NULL,
    description       VARCHAR(2000),
    uploaded_at       TIMESTAMPTZ,
    deleted_at        TIMESTAMPTZ,

    CONSTRAINT ck_case_documents_status CHECK (status IN
        ('UPLOADING', 'AVAILABLE', 'DELETED', 'FAILED')),
    CONSTRAINT ck_case_documents_size CHECK (file_size >= 0),
    -- uploaded_at is set exactly when the upload was confirmed against storage, so
    -- it is present for anything that reached AVAILABLE and for nothing that did
    -- not. A row that says AVAILABLE without one would be claiming a completion
    -- that never happened.
    CONSTRAINT ck_case_documents_uploaded_at CHECK (
        (status = 'AVAILABLE' AND uploaded_at IS NOT NULL)
        OR (status <> 'AVAILABLE')),
    CONSTRAINT ck_case_documents_deleted_at CHECK (
        (status = 'DELETED') = (deleted_at IS NOT NULL))
);

-- One object, one row.
CREATE UNIQUE INDEX uk_case_documents_storage_key ON documents.case_documents (storage_key);

-- "The documents on this matter", newest first — the only list endpoint there is,
-- and partial so the deleted rows it must never return are not in the index at all.
CREATE INDEX idx_case_documents_case ON documents.case_documents
    (organization_id, case_id, created_at DESC, id DESC) WHERE deleted_at IS NULL;

CREATE INDEX idx_case_documents_status ON documents.case_documents
    (organization_id, status) WHERE deleted_at IS NULL;

CREATE INDEX idx_case_documents_created ON documents.case_documents
    (organization_id, created_at DESC) WHERE deleted_at IS NULL;

-- Finds the abandoned uploads: rows that were never confirmed and never will be.
-- Nothing sweeps them in Phase 4; the index is here so that the job which
-- eventually does is a query, not a table scan.
CREATE INDEX idx_case_documents_uploading ON documents.case_documents (created_at)
    WHERE status = 'UPLOADING';

COMMENT ON COLUMN documents.case_documents.storage_key IS
    'Object key in the document bucket. Platform-generated, never caller-supplied, and never returned by the API.';
COMMENT ON COLUMN documents.case_documents.file_size IS
    'Declared at upload time, then overwritten with the size storage actually reports at completion.';
COMMENT ON COLUMN documents.case_documents.status IS
    'UPLOADING until confirmed against storage. AVAILABLE is the only state a download link is issued for.';

-- ------------------------------------------- widening the Phase 2 case timeline
-- A document arriving on a matter, or being removed from it, is something that
-- happened to that matter. It belongs on the timeline casework already owns, the
-- same way hearings and tasks joined it in V3 — a matter has one history.
ALTER TABLE casework.case_events DROP CONSTRAINT ck_case_events_type;
ALTER TABLE casework.case_events ADD CONSTRAINT ck_case_events_type CHECK (event_type IN
    ('CASE_CREATED', 'LAWYER_ASSIGNED', 'LAWYER_UNASSIGNED', 'CASE_STATUS_CHANGED', 'MANUAL_NOTE',
     'HEARING_SCHEDULED', 'HEARING_COMPLETED', 'HEARING_ADJOURNED', 'HEARING_CANCELLED',
     'TASK_CREATED', 'TASK_COMPLETED', 'TASK_CANCELLED',
     'DEADLINE_CREATED', 'DEADLINE_COMPLETED', 'DEADLINE_CANCELLED',
     'DOCUMENT_UPLOADED', 'DOCUMENT_DELETED'));
